In [153]:
# =====================================================
# IMPORT LIBRARIES
# =====================================================

import pandas as pd
import numpy as np
import os

print("Libraries imported successfully")

Libraries imported successfully

In [155]:
# =====================================================
# LOAD RAW EXCEL FILE
# =====================================================

file_path = r"C:\Users\Adhya\Hilton_Revenue_Analytics_Raw_Data.xlsx"


excel_data = pd.ExcelFile(file_path)


excel_data.sheet_names

['Bookings',
 'Hotel_KPI_Daily',
 'Competitor_Pricing',
 'Market_Events',
 'Guest_Reviews']

In [157]:
# =====================================================
# IMPORT ALL TABLES
# =====================================================


bookings = pd.read_excel(
    file_path,
    sheet_name="Bookings"
)


hotel_kpi = pd.read_excel(
    file_path,
    sheet_name="Hotel_KPI_Daily"
)


competitor = pd.read_excel(
    file_path,
    sheet_name="Competitor_Pricing"
)


events = pd.read_excel(
    file_path,
    sheet_name="Market_Events"
)


reviews = pd.read_excel(
    file_path,
    sheet_name="Guest_Reviews"
)


print("All tables loaded")

All tables loaded

In [159]:
# =====================================================
# CHECK DATA SIZE
# =====================================================


print("Bookings:", bookings.shape)

print("Hotel KPI:", hotel_kpi.shape)

print("Competitor:", competitor.shape)

print("Events:", events.shape)

print("Reviews:", reviews.shape)

Bookings: (50000, 16)
Hotel KPI: (731, 9)
Competitor: (10965, 8)
Events: (120, 5)
Reviews: (10000, 7)

In [161]:
# =====================================================
# MISSING VALUE CHECK
# =====================================================


datasets = {
    "Bookings": bookings,
    "Hotel KPI": hotel_kpi,
    "Competitor": competitor,
    "Events": events,
    "Reviews": reviews
}


for name, df in datasets.items():

    print("\n",name)

    print(
        df.isnull().sum()
    )

 Bookings
Reservation_ID         0
Booking_Date           0
Check_In_Date          0
Check_Out_Date         0
Booking_Window_Days    0
Room_Type              0
Booking_Channel        0
Customer_Segment       0
Country                0
Loyalty_Status         0
Length_of_Stay         0
Cancelled              0
Room_Rate              0
Total_Revenue          0
Adults                 0
Children               0
dtype: int64

 Hotel KPI
Date               0
Available_Rooms    0
Season             0
Demand_Level       0
Occupancy_Rate     0
Occupied_Rooms     0
ADR                0
Room_Revenue       0
RevPAR             0
dtype: int64

 Competitor
Date                  0
Competitor_Hotel      0
Room_Type             0
Competitor_ADR        0
Hilton_ADR            0
ADR_Gap               0
Market_Position       0
Market_Average_ADR    0
dtype: int64

 Events
Event_ID           0
Date               0
Event_Name         0
Event_Type         0
Expected_Demand    0
dtype: int64

 Reviews
Review_ID          0
Reservation_ID     0
Review_Date        0
Rating             0
Sentiment          0
Review_Category    0
Comments           0
dtype: int64

In [167]:
bookings.head()

,Reservation_ID,Booking_Date,Check_In_Date,Check_Out_Date,Booking_Window_Days,Room_Type,Booking_Channel,Customer_Segment,Country,Loyalty_Status,Length_of_Stay,Cancelled,Room_Rate,Total_Revenue,Adults,Children
0,HIL100000,2025-06-20,2025-11-12,2025-11-14,145,Standard Room,Expedia,Business,Japan,Diamond,2,No,241,482,2,0
1,HIL100001,2025-10-01,2025-12-25,2025-12-27,85,Standard Room,Direct Website,Family,Australia,Member,2,No,230,460,2,1
2,HIL100002,2025-10-07,2026-02-16,2026-02-22,132,Ocean View Room,Booking.com,Family,Canada,Non-Member,6,No,362,2172,2,2
3,HIL100003,2025-01-19,2025-03-06,2025-03-12,46,Ocean Front Room,Hilton Honors App,Leisure,United States,Non-Member,6,No,550,3300,2,0
4,HIL100004,2025-12-20,2026-02-25,2026-03-03,67,Suite,Expedia,Leisure,United States,Gold,6,No,758,4548,2,0

In [169]:
hotel_kpi.head()

,Date,Available_Rooms,Season,Demand_Level,Occupancy_Rate,Occupied_Rooms,ADR,Room_Revenue,RevPAR
0,2024-01-01,2860,Low Season,Medium,0.655353,1874,290,543460,190.020979
1,2024-01-02,2860,Low Season,Medium,0.636642,1820,293,533260,186.454545
2,2024-01-03,2860,Low Season,Medium,0.593973,1698,331,562038,196.516783
3,2024-01-04,2860,Low Season,Low,0.390252,1116,248,276768,96.772028
4,2024-01-05,2860,Low Season,Medium,0.666034,1904,299,569296,199.054545

In [171]:
competitor.head()

,Date,Competitor_Hotel,Room_Type,Competitor_ADR,Hilton_ADR,ADR_Gap,Market_Position,Market_Average_ADR
0,2024-01-01,Marriott Waikiki Beach,Standard Room,292,290,-2,Market Aligned,281.4
1,2024-01-01,Marriott Waikiki Beach,Ocean View Room,316,290,-26,Priced Lower Than Market,296.8
2,2024-01-01,Marriott Waikiki Beach,Ocean Front Room,338,290,-48,Priced Lower Than Market,300.0
3,2024-01-01,Hyatt Regency Waikiki,Standard Room,262,290,28,Priced Higher Than Market,281.4
4,2024-01-01,Hyatt Regency Waikiki,Ocean View Room,311,290,-21,Market Aligned,296.8

In [173]:
events.head()

  Event_ID       Date                    Event_Name Event_Type Expected_Demand
0  EVT1000 2024-01-01          New Year Celebration    Holiday       Very High
1  EVT1001 2024-03-15                  Spring Break    Holiday            High
2  EVT1002 2024-07-04  Independence Day Celebration    Holiday       Very High
3  EVT1003 2024-11-28          Thanksgiving Holiday    Holiday            High
4  EVT1004 2024-12-25             Christmas Holiday    Holiday       Very High

In [175]:
reviews.head()

,Review_ID,Reservation_ID,Review_Date,Rating,Sentiment,Review_Category,Comments
0,REV10000,HIL135905,2024-02-15,2,Negative,Food & Dining,High price compared to experience
1,REV10001,HIL128075,2025-01-11,3,Neutral,Room Quality,Average stay with good facilities
2,REV10002,HIL120490,2025-09-07,4,Positive,Check-in Experience,Great location and amazing experience
3,REV10003,HIL141002,2025-05-26,5,Positive,Room Quality,Great location and amazing experience
4,REV10004,HIL133813,2025-07-04,5,Positive,Check-in Experience,Great location and amazing experience

In [181]:
# Revenue generated per night

bookings["Revenue_Per_Night"] = (
    bookings["Total_Revenue"]
    /
    bookings["Length_of_Stay"]
)

In [183]:
# Create column Booking month

bookings["Booking_Month"] = (
    pd.to_datetime(bookings["Booking_Date"])
    .dt.month_name()
)

In [185]:
# Create column Check-in month

bookings["Check_In_Month"] = (
    pd.to_datetime(bookings["Check_In_Date"])
    .dt.month_name()
)

In [187]:
# Create column Stay category

def stay_category(days):

    if days <= 3:
        return "Short Stay"

    elif days <= 7:
        return "Medium Stay"

    else:
        return "Long Stay"


bookings["Stay_Category"] = (
    bookings["Length_of_Stay"]
    .apply(stay_category)
)

In [189]:
bookings.head()

,Reservation_ID,Booking_Date,Check_In_Date,Check_Out_Date,Booking_Window_Days,Room_Type,Booking_Channel,Customer_Segment,Country,Loyalty_Status,Length_of_Stay,Cancelled,Room_Rate,Total_Revenue,Adults,Children,Revenue_Per_Night,Booking_Month,Check_In_Month,Stay_Category
0,HIL100000,2025-06-20,2025-11-12,2025-11-14,145,Standard Room,Expedia,Business,Japan,Diamond,2,No,241,482,2,0,241.0,June,November,Short Stay
1,HIL100001,2025-10-01,2025-12-25,2025-12-27,85,Standard Room,Direct Website,Family,Australia,Member,2,No,230,460,2,1,230.0,October,December,Short Stay
2,HIL100002,2025-10-07,2026-02-16,2026-02-22,132,Ocean View Room,Booking.com,Family,Canada,Non-Member,6,No,362,2172,2,2,362.0,October,February,Medium Stay
3,HIL100003,2025-01-19,2025-03-06,2025-03-12,46,Ocean Front Room,Hilton Honors App,Leisure,United States,Non-Member,6,No,550,3300,2,0,550.0,January,March,Medium Stay
4,HIL100004,2025-12-20,2026-02-25,2026-03-03,67,Suite,Expedia,Leisure,United States,Gold,6,No,758,4548,2,0,758.0,December,February,Medium Stay

In [191]:
# Create column Month

hotel_kpi["Month"] = (
    pd.to_datetime(hotel_kpi["Date"])
    .dt.month_name()
)

In [193]:
# Create column Year

hotel_kpi["Year"] = (
    pd.to_datetime(hotel_kpi["Date"])
    .dt.year
)

In [195]:
# Validate Revenue per Available Room

hotel_kpi["Calculated_RevPAR"] = (
    hotel_kpi["Room_Revenue"]
    /
    hotel_kpi["Available_Rooms"]
)

In [197]:
hotel_kpi.head()

,Date,Available_Rooms,Season,Demand_Level,Occupancy_Rate,Occupied_Rooms,ADR,Room_Revenue,RevPAR,Month,Year,Calculated_RevPAR
0,2024-01-01,2860,Low Season,Medium,0.655353,1874,290,543460,190.020979,January,2024,190.020979
1,2024-01-02,2860,Low Season,Medium,0.636642,1820,293,533260,186.454545,January,2024,186.454545
2,2024-01-03,2860,Low Season,Medium,0.593973,1698,331,562038,196.516783,January,2024,196.516783
3,2024-01-04,2860,Low Season,Low,0.390252,1116,248,276768,96.772028,January,2024,96.772028
4,2024-01-05,2860,Low Season,Medium,0.666034,1904,299,569296,199.054545,January,2024,199.054545

In [199]:
# Create column Pricing Index

competitor["Pricing_Index"] = (
    competitor["Hilton_ADR"]
    /
    competitor["Market_Average_ADR"]
)

In [201]:
competitor.head()

,Date,Competitor_Hotel,Room_Type,Competitor_ADR,Hilton_ADR,ADR_Gap,Market_Position,Market_Average_ADR,Pricing_Index
0,2024-01-01,Marriott Waikiki Beach,Standard Room,292,290,-2,Market Aligned,281.4,1.030561
1,2024-01-01,Marriott Waikiki Beach,Ocean View Room,316,290,-26,Priced Lower Than Market,296.8,0.977089
2,2024-01-01,Marriott Waikiki Beach,Ocean Front Room,338,290,-48,Priced Lower Than Market,300.0,0.966667
3,2024-01-01,Hyatt Regency Waikiki,Standard Room,262,290,28,Priced Higher Than Market,281.4,1.030561
4,2024-01-01,Hyatt Regency Waikiki,Ocean View Room,311,290,-21,Market Aligned,296.8,0.977089

In [203]:
# Create column Review Month

reviews["Review_Month"] = (
    pd.to_datetime(reviews["Review_Date"])
    .dt.month_name()
)

In [205]:
# Create column Rating Category

def rating_category(rating):

    if rating >=4:
        return "Satisfied"

    elif rating ==3:
        return "Neutral"

    else:
        return "Dissatisfied"


reviews["Rating_Category"] = (
    reviews["Rating"]
    .apply(rating_category)
)

In [207]:
reviews.head()

,Review_ID,Reservation_ID,Review_Date,Rating,Sentiment,Review_Category,Comments,Review_Month,Rating_Category
0,REV10000,HIL135905,2024-02-15,2,Negative,Food & Dining,High price compared to experience,February,Dissatisfied
1,REV10001,HIL128075,2025-01-11,3,Neutral,Room Quality,Average stay with good facilities,January,Neutral
2,REV10002,HIL120490,2025-09-07,4,Positive,Check-in Experience,Great location and amazing experience,September,Satisfied
3,REV10003,HIL141002,2025-05-26,5,Positive,Room Quality,Great location and amazing experience,May,Satisfied
4,REV10004,HIL133813,2025-07-04,5,Positive,Check-in Experience,Great location and amazing experience,July,Satisfied

In [209]:
# Create column Events Month

events["Event_Month"] = (
    pd.to_datetime(events["Date"])
    .dt.month_name()
)

In [211]:
events.head()

,Event_ID,Date,Event_Name,Event_Type,Expected_Demand,Event_Month
0,EVT1000,2024-01-01,New Year Celebration,Holiday,Very High,January
1,EVT1001,2024-03-15,Spring Break,Holiday,High,March
2,EVT1002,2024-07-04,Independence Day Celebration,Holiday,Very High,July
3,EVT1003,2024-11-28,Thanksgiving Holiday,Holiday,High,November
4,EVT1004,2024-12-25,Christmas Holiday,Holiday,Very High,December

In [213]:
# Phase 3: SQL Database Creation & Business Analysis

In [215]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.7.0-py2.py3-none-any.whl.metadata (11 kB)
Downloading mysql_connector_python-9.7.0-py2.py3-none-any.whl (480 kB)
   ---------------------------------------- 0.0/480.6 kB ? eta -:--:--
   - ------------------------------------- 20.5/480.6 kB 640.0 kB/s eta 0:00:01
   --------------- ------------------------ 184.3/480.6 kB 2.2 MB/s eta 0:00:01
   ---------------------------------------- 480.6/480.6 kB 4.3 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.7.0

In [229]:
import mysql.connector

In [245]:
import mysql.connector


connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="YOURPASSWORD",
    database="hilton_revenue_analytics"
)


cursor = connection.cursor()


print("Connected successfully")

Connected successfully

In [247]:
cursor.execute("SHOW TABLES;")

cursor.fetchall()

[('bookings',),
 ('competitor_pricing',),
 ('guest_reviews',),
 ('hotel_kpi_daily',),
 ('market_events',)]

In [249]:
!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\adhya\anaconda3\lib\site-packages (2.0.30)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\adhya\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\adhya\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)

In [261]:
from sqlalchemy import create_engine


engine = create_engine(
    "mysql+mysqlconnector://root:YOURPASSWORD@127.0.0.1:3306/hilton_revenue_analytics"
)


print("Engine created")

Engine created

In [267]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus


password = quote_plus("YOURPASSWORD")


engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost:3306/hilton_revenue_analytics"
)


print("Engine created successfully")

Engine created successfully

In [269]:
from sqlalchemy import text


with engine.connect() as conn:
    
    result = conn.execute(
        text("SELECT DATABASE();")
    )
    
    print(result.fetchall())

[('hilton_revenue_analytics',)]

In [271]:
bookings.to_sql(
    name="bookings",
    con=engine,
    if_exists="replace",
    index=False
)


print("Bookings uploaded successfully!")

Bookings uploaded successfully!

In [273]:
pd.read_sql(
    "SELECT COUNT(*) AS total_rows FROM bookings;",
    engine
)

   total_rows
0       50000

In [275]:
hotel_kpi.to_sql(
    name="hotel_kpi_daily",
    con=engine,
    if_exists="replace",
    index=False
)

print("Hotel KPI uploaded successfully!")

Hotel KPI uploaded successfully!

In [277]:
pd.read_sql(
    "SELECT COUNT(*) AS total_rows FROM hotel_kpi_daily;",
    engine
)

   total_rows
0         731

In [279]:
competitor.to_sql(
    name="competitor_pricing",
    con=engine,
    if_exists="replace",
    index=False
)

print("Competitor Pricing uploaded successfully!")

Competitor Pricing uploaded successfully!

In [281]:
pd.read_sql(
    "SELECT COUNT(*) AS total_rows FROM competitor_pricing;",
    engine
)

   total_rows
0       10965

In [283]:
events.to_sql(
    name="market_events",
    con=engine,
    if_exists="replace",
    index=False
)

print("Market Events uploaded successfully!")

Market Events uploaded successfully!

In [285]:
pd.read_sql(
    "SELECT COUNT(*) AS total_rows FROM market_events;",
    engine
)

   total_rows
0         120

In [287]:
reviews.to_sql(
    name="guest_reviews",
    con=engine,
    if_exists="replace",
    index=False
)

print("Guest Reviews uploaded successfully!")

Guest Reviews uploaded successfully!

In [289]:
pd.read_sql(
    "SELECT COUNT(*) AS total_rows FROM guest_reviews;",
    engine
)

   total_rows
0       10000

In [291]:
tables_check = pd.read_sql(
    """
    SELECT 
        table_name
    FROM information_schema.tables
    WHERE table_schema='hilton_revenue_analytics';
    """,
    engine
)

tables_check

           TABLE_NAME
0            bookings
1  competitor_pricing
2       guest_reviews
3     hotel_kpi_daily
4       market_events